config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations'
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/x_nodeinfo2#show', as: :xnodeinfo2
  get '.well-known/nodeinfo', to: 'well_known/nodeinfo2#show', as: :nodeinfo2
  get 'nodeinfo/2.0', to: 'well_known/nodeinfo2#show_real', as: :nodeinfo2_real
  get 'manifest', to: 'manifest#show', as: :manifest, defaults: { format: 'application/manifest+json' }

  get 'accounts/:id', to: 'accounts/stories#hot', as: :network_account

  get :design, to: 'static#design'

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  resource :feed, defaults: { format: 'atom' } do
    get :hot, to: 'stories#index'
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  resource :dashboard, only: [:show] do
    get :recent, on: :member
  end

  namespace :search do
    resources :posts, path: '/', only: [:index]
    resources :comments, only: [:index]
    resources :users, only: [:index]
  end

  resources :stories, path: :posts do
    get :recent, on: :collection

    resource :flag, only: %i[new create edit update]
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection

    resource :flag, only: %i[new create edit update]
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      namespace :markdown do
        get :preview
      end

      resources :stories, only: [] do
        post :toggle_like, on: :member
        post :scrap, on: :member
        delete :destroy, on: :member, as: :delete
      end

      resources :comments, only: [:new, :create, :edit, :update, :destroy] do
        post :toggle_like, on: :member
      end

      resources :accounts, only: [] do
        post :toggle_follow, on: :member
      end

      resources :tags, only: [] do
        post :toggle_follow, on: :member
      end
    end

    namespace :v1, defaults: { format: :json } do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update, :destroy]
    resource :preferences, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
    resources :accounts, except: [:delete] do
      post :suspend, on: :member
      post :silence, on: :member
      post :unsilence, on: :member
    end
    resources :domain_blocks, except: [:edit, :update]
    resources :flags, except: [:new, :create, :delete] do
      post :resolve, on: :member
      post :unresolve, on: :member
    end
  end
end

app/models/story.rb
# frozen_string_literal: true

class Story < ApplicationRecord
  include HasUUIDConcern
  include ActivityPub::ObjectConcern
  include PgSearch

  Gutentag::ActiveRecord.call(self)

  HOT_DAYS_LIMIT = 40

  attr_accessor :tag_list

  pg_search_scope :search, against: { title: 'A', description: 'B' },
                           using: { tsearch: { prefix: true } }

  belongs_to :account, counter_cache: true, optional: true
  has_many :comments, dependent: :destroy
  belongs_to :url_meta, optional: true
  has_many :likes, as: :likeable
  belongs_to :group, optional: true
  has_many :flags, as: :flaggable

  validates :url, allow_blank: true, uniqueness: true

  delegate :thumb, :thumb_url, :thumb_data?,
           to: :url_meta,
           allow_nil: true

  def article?
    !url.present?
  end

  def link?
    url.present?
  end

  def object_type
    article? ? :article : :page
  end
end

app/controllers/accounts/stories_controller.rb
# frozen_string_literal: true

class Accounts::StoriesController < Accounts::BaseController
  layout 'application'

  before_action :set_account_liked_story_ids

  def hot
    @account = find_account
    @feed_title = "Hot stories by #{@account}"
    set_meta_tags @account.to_meta_tags.merge(title: @feed_title)

    stories = StoriesQuery.new.hot
    stories = StoriesQuery.new(stories).for_account(@account)

    @stories = stories.page(params[:page])

    respond_to do |format|
      format.html { render :index }
      format.atom { render 'stories/index' }
      format.json do
        render json: ActivityPub::ActorSerializer.new(@account),
               with_context: true,
               content_type: 'application/activity+json'
      end
    end
  end

  def recent
    @account = find_account
    @feed_title = "Recent stories by #{@account}"
    set_meta_tags @account.to_meta_tags.merge(title: @feed_title)

    stories = StoriesQuery.new.recent
    stories = StoriesQuery.new(stories).for_account(@account)

    @stories = stories.page(params[:page])

    respond_to do |format|
      format.html { render :index }
      format.atom { render 'stories/index' }
    end
  end
end

app/controllers/api/ujs/stories_controller.rb
# frozen_string_literal: true

class Api::Ujs::StoriesController < Api::Ujs::BaseController
  def toggle_like
    user_needed
    story = find_story
    authorize story

    outcome = Stories::ToggleLike.run(story: story, account: current_user.account)
    set_account_liked_story_ids

    render 'stories/_story', layout: false, locals: { story: outcome.result.likeable }
  end

  def scrap
    story = find_story
    authorize story

    Stories::Rescrap.run(story: story, user: current_user)

    head :no_content
  end

  def destroy
    story = find_story
    authorize story

    Stories::DeleteJob.perform_later(story.id)

    head :ok
  end

  private

  def find_story
    ActivityPubPost.find(params[:id])
  end
end

app/controllers/stories_controller.rb
# frozen_string_literal: true

class StoriesController < ApplicationController
  layout 'application'

  before_action :authenticate_user!, only: %i[new create edit update]
  before_action :set_account_liked_story_ids

  def index
    @page_title = 'Hot stories'
    @feed_title = @page_title

    stories = StoriesQuery.new.hot
    stories = StoriesQuery.new(stories).without_silenced

    @stories = stories.page(params[:page])

    respond_to do |format|
      format.html { render :index }
      format.atom { render :index }
    end
  end

  def recent
    @page_title = 'Recent stories'
    @feed_title = @page_title

    stories = StoriesQuery.new.recent
    stories = StoriesQuery.new(stories).without_silenced

    @stories = stories.page(params[:page])

    respond_to do |format|
      format.html { render :index }
      format.atom { render :index }
    end
  end

  def show
    set_account_liked_comment_ids

    @story = ActivityPubPost.find(params[:id])
    @comments = @story.children.includes(:account, :root_cached).hash_tree
    @comment = Comments::Create.new(
      parent_id: @story.id
    )

    respond_to do |format|
      format.html
      format.json do
        render json: ActivityPub::StorySerializer.new(@story),
               with_context: true,
               content_type: 'application/activity+json'
      end
    end
  end

  def new
    @story = Stories::Create.new(*new_story_params)
    authorize @story
  end

  def create
    authorize Stories::Create

    outcome = Stories::Create.run(
      name: params.fetch(:story)[:name],
      url: params.fetch(:story)[:url],
      content_source: params.fetch(:story)[:content_source],
      tag_list: params.fetch(:story)[:tag_list],
      account: current_account
    )

    if outcome.valid?
      path = outcome.result.decorate.path
      redirect_to path, notice: 'Story has been created'
    else
      @story = outcome
      render :new
    end
  end

  def edit
    story = find_story
    authorize story

    @story = Stories::Update.new(
      story: story,
      url: story.url,
      name: story.name,
      tag_list: story.tag_names.join(', '),
      content_source: story.content_source,
    )
  end

  def update
    story = find_story
    authorize story

    outcome = Stories::Update.run(
      story: story,
      url: params.fetch(:story)[:url],
      name: params.fetch(:story)[:name],
      tag_list: params.fetch(:story)[:tag_list],
      content_source: params.fetch(:story)[:content_source],
      account: current_account
    )

    if outcome.valid?
      path = outcome.result.decorate.path
      redirect_to path, notice: 'Story has been updated'
    else
      @story = outcome
      render :edit
    end
  end

  private

  def new_story_params
    params.permit(:url, :title)
  end

  def find_story
    ActivityPubPost.find(params[:id])
  end
end

app/controllers/tags/stories_controller.rb
# frozen_string_literal: true

class Tags::StoriesController < ApplicationController
  layout 'application'

  before_action :set_account_liked_story_ids

  before_action { set_jumpbox_link(find_tag) }

  def hot
    @tag = find_tag
    stories = StoriesQuery.new.hot
    stories = StoriesQuery.new(stories).tagged_with([@tag.name])

    @feed_title = "Hot stories in #{@tag.decorate}"
    set_meta_tags @tag.decorate.to_meta_tags.merge(title: @feed_title)

    @stories = stories.page(params[:page])

    respond_to do |format|
      format.html { render :index }
      format.atom { render 'stories/index' }
    end
  end

  def recent
    @tag = find_tag
    stories = StoriesQuery.new.recent
    stories = StoriesQuery.new(stories).tagged_with([@tag.name])

    @feed_title = "Recent stories in #{@tag.decorate}"
    set_meta_tags @tag.decorate.to_meta_tags.merge(title: @feed_title)

    @stories = stories.page(params[:page])

    respond_to do |format|
      format.html { render :index }
      format.atom { render 'stories/index' }
    end
  end

  private

  def find_tag
    @find_tag ||= Gutentag::Tag.find_by!(name: params[:tag_name]).decorate
  end
end

app/views/stories/_story/_meta_primary.html.slim
- show_tags = local_assigns.key?(:show_tags) ? show_tags : true

- if account.present?
  li.no-dot
    - if account.id.present?
      | @#{link_to account.username, account.path, class: 'p-author'}
    - else
      = account.username_with_at

li
  - if story.article?
    span.label.label--secondary.up = t('text')
  - else
    = story.url_domain

- if show_tags
  = render 'stories/_story/tags', presenter: presenter

app/views/stories/_story/_meta_secondary.html.slim
li.list-inline-item
  = link_to story_path(story), class: 'story-row__comments-count u-url' do
    i.fe.fe-message-circle
    | #{story.children_count}
    span= t('.comments')

li.list-inline-item
  = link_to story_path(story) do
    = t('.posted')

    time.ml--xxs.dt-published(
      data-controller="time-ago"
      data-datetime=story.created_at.iso8601
      datetime=story.created_at.iso8601
    )
      = story.created_at

- if story.modified_count.positive?
  li
    span.text--warning(title=t('.last_edited_at', modified_at: story.modified_at))
      i.fe.fe-edit.mr--xxs
      = story.modified_count

- if presenter.more_actions?
  li(data-controller="dropdown" data-dropdown-placement="bottom-end")
    a(
      href="javascript:void(0);"
      data-turbolinks="false"
      data-target="dropdown.toggle"
      data-action="click->dropdown#toggle click@window->dropdown#hide"
    )
      = t('.more')

    ul.dropdown(data-target="dropdown.dropdown" data-dropdown-placement="bottom-end")
      - if policy(story).edit?
        li.dropdown__item
          = link_to t('.edit'), edit_story_path(story)

      - if policy(story).scrap?
        li.dropdown__item
          a(
            href="#"
            data-action="click->story#scrap"
            data-action-path=scrap_api_ujs_story_path(story)
          ) Scrap again

      - if policy(Flag).create?
        li.dropdown__item
          a(
            href=new_story_flag_path(story)
          ) Flag

      - if policy(story).destroy?
        li.dropdown__divider
        li.dropdown__item
          a(
            href="javascript:void(0)"
            data-action="click->story#delete"
            data-action-path=delete_api_ujs_story_path(story)
          ) Delete

app/views/stories/_story/_tags.html.slim
- presenter.primary_tags.each do |tag|
  li.no-dot
    | ##{link_to tag.name, tag.path, class: 'p-category'}

- if presenter.more_tags.any?
  li.list-inline-item(data-controller="dropdown")
    a(href="javascript:void(0)" data-target="dropdown.toggle" data-action="click->dropdown#toggle click@window->dropdown#hide")
      = t('.presenter_more', presenter: (presenter.more_tags.size))

    ul.dropdown(data-target="dropdown.dropdown")
      - presenter.more_tags.each do |tag|
        li.dropdown__item
          = link_to "##{tag.name}", tag.path, class: 'p-category'